name: Maven Test

on:
  push:
    branches:
      - main  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

      #Step to create .env file from GitHub Secrets
    - name: Setup .env file
      run: |
        echo -e "EXCHANGE_RATE_API_KEY=${{ secrets.EXCHANGE_RATE_API_KEY }}\SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" > HW1/backend/.env
      shell: bash

    - name: Build and run unit tests with Maven
      run: cd HW1/backend && mvn test
      continue-on-error: false

    - name: Run integration tests with Maven
      run: cd HW1/backend && mvn failsafe:integration-test
      continue-on-error: false
